/**
 * Curated list of Indian cities used by the checkout city autocomplete.
 * Sorted alphabetically. Includes major metros, tier-1, tier-2 and many
 * tier-3 cities so users in most populated areas find theirs quickly.
 */
export const INDIAN_CITIES: readonly string[] = [
  'Adoni', 'Agartala', 'Agra', 'Ahmedabad', 'Ahmednagar', 'Aizawl', 'Ajmer', 'Akola',
  'Alappuzha', 'Aligarh', 'Allahabad', 'Alwar', 'Ambala', 'Ambattur', 'Ambernath',
  'Amravati', 'Amritsar', 'Anand', 'Anantapur', 'Arrah', 'Asansol', 'Aurangabad',
  'Avadi', 'Bahraich', 'Ballia', 'Bally', 'Bardhaman', 'Bareilly', 'Bathinda',
  'Begusarai', 'Belgaum', 'Bellary', 'Bengaluru', 'Berhampore', 'Berhampur',
  'Bhagalpur', 'Bharatpur', 'Bhatpara', 'Bhavnagar', 'Bhilai', 'Bhilwara',
  'Bhimavaram', 'Bhiwandi', 'Bhiwani', 'Bhopal', 'Bhubaneswar', 'Bhuj', 'Bidar',
  'Bidhannagar', 'Bihar Sharif', 'Bijapur', 'Bikaner', 'Bilaspur', 'Bokaro',
  'Brahmapur', 'Bulandshahr', 'Burhanpur', 'Buxar', 'Chandigarh', 'Chapra',
  'Chennai', 'Chinsurah', 'Chittoor', 'Coimbatore', 'Cuttack', 'Daman',
  'Danapur', 'Darbhanga', 'Davanagere', 'Dehradun', 'Delhi', 'Deoghar', 'Dewas',
  'Dhanbad', 'Dharmavaram', 'Dhule', 'Dibrugarh', 'Dindigul', 'Diu', 'Durg',
  'Durgapur', 'Eluru', 'Erode', 'Etawah', 'Faridabad', 'Farrukhabad', 'Firozabad',
  'Gandhidham', 'Gandhinagar', 'Gangtok', 'Gaya', 'Ghaziabad', 'Gorakhpur',
  'Gulbarga', 'Guna', 'Guntakal', 'Guntur', 'Gurugram', 'Guwahati', 'Gwalior',
  'Hajipur', 'Haldia', 'Hapur', 'Haridwar', 'Hindupur', 'Hisar', 'Hospet',
  'Howrah', 'Hubli', 'Hyderabad', 'Ichalkaranji', 'Imphal', 'Indore', 'Itanagar',
  'Jabalpur', 'Jaipur', 'Jalandhar', 'Jalgaon', 'Jalna', 'Jammu', 'Jamnagar',
  'Jamshedpur', 'Jaunpur', 'Jhansi', 'Jodhpur', 'Junagadh', 'Kadapa', 'Kakinada',
  'Kalyan', 'Kanchipuram', 'Kanpur', 'Karaikudi', 'Karimnagar', 'Karnal',
  'Karur', 'Katihar', 'Khammam', 'Khandwa', 'Kharagpur', 'Kishanganj', 'Kochi',
  'Kohima', 'Kolar', 'Kolhapur', 'Kolkata', 'Kollam', 'Korba', 'Kota', 'Kottayam',
  'Kozhikode', 'Kulti', 'Kumbakonam', 'Kurnool', 'Latur', 'Loni', 'Lucknow',
  'Ludhiana', 'Machilipatnam', 'Madanapalle', 'Madhyamgram', 'Madurai', 'Mahbubnagar',
  'Maheshtala', 'Malda', 'Malegaon', 'Mangalore', 'Mathura', 'Mau', 'Medininagar',
  'Meerut', 'Mehsana', 'Mira-Bhayandar', 'Mirzapur', 'Moradabad', 'Morbi',
  'Morena', 'Motihari', 'Mumbai', 'Munger', 'Muzaffarnagar', 'Muzaffarpur',
  'Mysuru', 'Nadiad', 'Nagaon', 'Nagercoil', 'Nagpur', 'Naihati', 'Nanded',
  'Nandyal', 'Nashik', 'Navi Mumbai', 'Navsari', 'Nellore', 'New Delhi', 'Nizamabad',
  'Noida', 'North Dumdum', 'Ongole', 'Orai', 'Panchkula', 'Panihati', 'Panipat',
  'Panvel', 'Parbhani', 'Patiala', 'Patna', 'Pimpri-Chinchwad', 'Pondicherry',
  'Porbandar', 'Port Blair', 'Prayagraj', 'Proddatur', 'Pune', 'Puri', 'Purnia',
  'Raebareli', 'Raichur', 'Raiganj', 'Raipur', 'Rajahmundry', 'Rajkot', 'Rajpur Sonarpur',
  'Ramagundam', 'Rampur', 'Ranchi', 'Ratlam', 'Raurkela', 'Rewa', 'Rishikesh',
  'Rohtak', 'Rourkela', 'Sagar', 'Saharanpur', 'Saharsa', 'Salem', 'Sambalpur',
  'Sambhal', 'Sangli-Miraj', 'Sasaram', 'Satara', 'Satna', 'Secunderabad',
  'Serampore', 'Shahjahanpur', 'Shillong', 'Shimla', 'Shimoga', 'Shivpuri',
  'Sikar', 'Silchar', 'Siliguri', 'Singrauli', 'Sirsa', 'Sitapur', 'Solapur',
  'Sonipat', 'Sri Ganganagar', 'Srikakulam', 'Srinagar', 'Sultanpur', 'Surat',
  'Surendranagar', 'Suryapet', 'Tadepalligudem', 'Tadipatri', 'Tenali', 'Thane',
  'Thanjavur', 'Thiruvananthapuram', 'Thoothukudi', 'Thrissur', 'Tinsukia',
  'Tiruchirappalli', 'Tirunelveli', 'Tirupati', 'Tiruppur', 'Tiruvannamalai',
  'Tiruvottiyur', 'Tumkur', 'Udaipur', 'Udupi', 'Ujjain', 'Ulhasnagar', 'Uluberia',
  'Unnao', 'Vadodara', 'Varanasi', 'Vasai-Virar', 'Vellore', 'Vijayawada',
  'Vijayanagaram', 'Vellore', 'Visakhapatnam', 'Warangal', 'Wardha', 'Yamunanagar',
];
